### ISSUE TITLE
Click on Start activity sensing while navigating from Home page again after stopping it once

### ISSUE THREAD

**Issue by Lipsaray** [nithyakonda/LupusApp#11]
Expected: Should continue the count from where it stopped
Actual: Starts counting from zero again

**Comment by nithyakonda** [comment]
In this page the step count shown is only to assess and set the sensitivity. 
It is ok if it starts from 0. 
However I made changes to the code so that the step count in incremented when user starts/stops activity sensing. This data will be reflected in the home page not here, because that is where the user is supposed to check his step count.

Its not a bug!
